
project:
  type: website
  resources:
  - images/*
bibliography: references.bib
website:
  title: "Introduction to Computational Social Science"
  sidebar:
    pinned: true
    contents:
    - section: "Information"
      contents:
      - syllabus.qmd
      - readings-overview.qmd
    - section: "Sections"
      text: "Framing"
      #contents: sections/*
      contents:
      - sections/defining-computational-social-science.qmd
      - sections/prediction-explanation.qmd
      - sections/ethics-and-best-practices.qmd
      - sections/experiments-and-causal-inference.qmd
format:
  html:
    toc: true
  pdf:
    fig-pos: H
